#! /bin/bash
# /etc/init.d/carportopener

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting carportopener"
    # Turn on GPIO 7 to keep relay off
    gpio write 7 1
    gpio mode 7 out
    # Turn on GPIO 3, outputs signal read in by GPIO 0 for carport status
    gpio write 2 1
    gpio mode 2 out
    ;;
  stop)
    echo "Stopping carportopener"
    ;;
  *)
    echo "Usage: /etc/init.d/carportopener {start|stop}"
    exit 1
    ;;
esac

exit 0
